#index:
#    path: /
#    controller: App\Controller\DefaultController::index

showCustomers:
  path: /api/customers
  controller: App\Controller\CustomerController::showCustomers

createCustomer:
  path: /api/customer
  controller: App\Controller\CustomerController::createCustomer
  methods: POST